#!/usr/bin/env python

from subprocess import Popen
import os
import time

if 'DELAY' in os.environ:
    time.sleep(int(os.environ['DELAY']))

CONFIG_FILE = "deployment.ini"

Popen("cp -Rv data.default/* data", shell=True).wait()

config_entries = []
with open(CONFIG_FILE, "r") as config:
    for line in config.readlines():
        if "=" in line:
            config_key = line.split("=", 1)[0].strip()
            for env_key, env_value in os.environ.iteritems():
                if env_key.lower() == config_key.strip().lower().replace(".","_"):
                    line = "{key} = {value}\n".format(key=config_key, value=env_value)
            
        config_entries.append(line)
        
with open(CONFIG_FILE, "w") as config:
    config.writelines(config_entries)

Popen(["paster", "setup-app", CONFIG_FILE]).wait()

serve_command = ["paster", "serve"]

if 'RELOAD' in os.environ:
    serve_command.append("--reload")

serve_command.append(CONFIG_FILE)

print serve_command
Popen(serve_command).wait()
